name: continuous-deployment
run-name: Deploy do site para o servidor de produção
on:
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          push: true
          tags: murilomuniz/site-faculdade:latest

      - name: Azure Web App Deploy
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: aula-devops-cd
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: murilomuniz/site-faculdade:latest
